version: "3"
services:
  rpi-python:
    build: .
    privileged: true
    cap_add:
      - SYS_RAWIO
    devices:
    - /dev/mem:/dev/mem
    environment:
    - CHANNEL_SWITCH: 17
    - CHANNEL_LED: 18
    - PWM_CYCLE: 0.005
    - NUM_FLASHES: 3
